### ISSUE TITLE
Testing current CV model on old Tahome Data 

### ISSUE THREAD

**Issue by sarda-devesh** [ProjectSidewalk/sidewalk-cv-tools#6]
Just a reminder that I need to test the accuracy, recall,precision and other data points of our CV's performance on the Tohme data set on different label types

**Comment by galenweld** [comment]
FYI tohme only contains labels for curb ramps and Missing curb ramps, not
for any other label types, so we'll only be focusing on those.

In the past, we had trouble finding the labels for missing curb ramps, so
unless we can find those, we'll be focusing just on curb ramps.

**Comment by sarda-devesh** [comment]
Ok I will focus on Curb Ramp only and not any other label types while doing these calculations. Right now on the hard disk that you gave with the Seattle panos I have this tohme_data.tar file but opening it I found that it only had the meta.xml files for all the panos but not any of the images. Thus I was wondering where I would be able to get those images?

**Comment by sarda-devesh** [comment]
I ran our CV model on the Tohme data and the results are quite promising. First of all, I combine overlapping boxes to ensure that we don't run the CV model on the same location twice.To convert between the street view x and street view y given in the tohme dataset to pixel x and y coordinate in the image, I first got the pano yaw degree (let us call that py) from the metadata xml file associated with the panorama and then calculated a xml_value based on the following relationship: 

`xml_value = 360 - ((py + 180) % 360)` 

Then using the Xml_value I calculated pixel x and y coordinates given the street view x (sv_x) and street view y (sv_y) using the following formulas: 

`x = (xml_value/360.0 * GSV_IMAGE_WIDTH + sv_x) % GSV_IMAGE_WIDTH`

and 

`y = GSV_IMAGE_HEIGHT / 2 - sv_y`

While the range for the confidence of our CV model is usually [-5,5], the range of our confidence was [0,10] with Kotoro's data set which indicates that CV was really sure and could easily pick up the objects in the image, keeping in mind that we were testing it on the easier label types. When we look at the Curb Ramp graph we see close to a ideal graph where the model approaches a 100% agreement a relatively low confidence value and stays there for the higher confidence values with there being a significant amount of data points for each bin, each of which has a width of 1.0. 

For No Curb Ramps, even though we see a wanted trend up to a confidence level of 7 with it approaching close a 100% agreement at that confidence level, the agreement starts to drop off again. I believe that this trend is because we have so low values for those confidence levels for no curb ramp as indicated by the totals which cause the agreement to fall. I do believe that if had a higher number of data points we would have seen a similar trend as in curb ramps but still the results are pretty nice. 


<img width="328" alt="Tohme_Third" src="https://user-images.githubusercontent.com/32046390/62640794-365ce000-b8f7-11e9-8ebc-1a23f86ad33b.png">

**Comment by galenweld** [comment]
Thanks Devesh for the update and excellent results.

In these posts, especially for Tohme, where we're hoping to confirm what we found in the ASSETS paper, it's really important that you make two things clear: what our results were, and how they compare to our expectations.

For clarity, here's the important bit: Our model had 95% and 90% curb ramp precision and recall, respectively, compared with 93% and 97% on the ASSETS D.C. test set.

Our model had 79% and 63% missing curb ramp precision and recall, respectively, compared with 77% and 62% on the ASSETS D.C. test set.

Overall, these results are encouraging, and very much validate our findings in the paper.

Thanks for the good work everyone!

**Comment by sarda-devesh** [comment]
Going back and comparing the above results with the results from the original Tohme paper we see that the model from the Tohme paper had a precision of 83% (the model from the assets paper has a precision of 95%) and the model from the Tohme paper had a recall of 86% (the model from the assets paper has a recall of 90%) for Curb Ramps
